[package]
name = "Day8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1.8.1"
once_cell="1.19.0"
rayon="1.8.0"
num="0.4.1"